services:
  app:
    build: .
    extra_hosts:
      - 'host.docker.internal:host-gateway'    
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: ['yarn','dev','--host']
